{{- range $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ include "crm-backend.namespace" . }}
  labels:
    app: {{ $service.name }}
    chart: {{ include "crm-backend.chart" . }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ $service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ $service.name }}
  sessionAffinity: None
{{- end }}
